Unbreak on BSDs by updating to gpakosz/whereami@6eb1195
lib/libvital.so.0.1.0: undefined reference to `kwiver::vital::wai_getModulePath(char*, int, int*)'
lib/libvital.so.0.1.0: undefined reference to `kwiver::vital::wai_getExecutablePath(char*, int, int*)'
c++: error: linker command failed with exit code 1 (use -v to see invocation)